name: generate-and-upload-card

on:
  schedule:
    - cron: "0 */24 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: generate github stats card
        uses: LuciNyan/pixel-profile/action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          outputs: |
            dist/github-stats?username=pradanaadn&screen_effect=false&theme=fuji&dithering=true&hide=avatar
            dist/github-stats-dark?username=pradanaadn&theme=crt
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
